deviceName: WT32-ETH01 EVSE

button:
  gpio: 14

pilot:
  gpio: 33
  adcChannel: 7
  levels: [2410, 2104, 1797, 1491, 265]

acRelay:
  gpios: [32]

onewire:
  gpio: 17
  temperatureSensor: true

ota:
  channels:
    - name: stable
      path: https://dzurikmiroslav.github.io/esp32-evse/ota/stable/esp32.json
